# Generated by Django 4.0.8 on 2022-10-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_dob_user_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cars_owned',
            field=models.ManyToManyField(to='users.car'),
        ),
    ]
